=== piripinui/DE-CIM-Model/DE_CIM_Model/abb.eam.asset-1.0.0.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "abb.eam.asset-1.0.0.json",
    "type": "object",
    "title": "Generic Asset Model",
    "description": "The generic description of an Asset",

    "properties": {
        "assetId": {
            "$ref": "abb.eam.asset.identity-1.0.0.json"
        },
        "assetDescription": {
            "description": "An informal description of the Asset",
            "type": "string"
        },
        "assetStatus": {
            "$ref": "abb.eam.asset.statustypes-1.0.0.json"
        },
        "assetCriticality": {
            "$ref": "abb.eam.asset.criticalitytypes-1.0.0.json"
        },
        "industryAttributes": {
          "description": "A set of additional attributes associated with a specific asset class used in a given industry e.g. transformers, buses etc",
          "type": "array",
          "default": [],
          "items": {
              "$ref": "abb.eam.asset.industryattribute-1.0.0.json"
          }
        },
        "customAttributes": {
            "description": "A set of additional attributes associated with the Asset",
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.asset.customattribute-1.0.0.json"
            }
        },
        "workOrders": {
            "description": "Work Orders that are associated with this Asset",
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.workorder-1.0.0.json"
            }
        },
        "location": {
            "$ref": "abb.eam.location-1.0.0.json"
        },
        "parentAssetId": {
            "description": "This Asset's parent Asset (if any)",
            "type": "string"
        },
        "subassets": {
            "description": "This Asset's child Assets (if any)",
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.asset-1.0.0.json"
            }
        },
        "components": {
            "description": "This Asset's sub-components (if any)",
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.component-1.0.0.json"
            }
        },
        "features": {
            "description": "This Asset's features (if any)",
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.feature-1.0.0.json"
            }
        }
    },
    "required": [
        "assetId",
        "assetDescription",
        "assetStatus",
        "industryAttributes",
        "customAttributes"
    ],
    "additionalProperties": false
}

=== piripinui/DE-CIM-Model/DE_CIM_Model/test_data/simple_cb_test.json
{
  "assetId": "DE-CB218746283746238",
  "assetDescription": "Circuit Breaker in Big Substation",
  "assetStatus": "Installed",
  "industryAttributes": [
    {
      "type": {
        "manufacturer": "ABB",
        "type": "Emax 2"
      },
      "installationDate": "01/01/99"
    }
  ],
  "customAttributes": [
    {
      "name": "admsId",
      "value": {
        "id": "CB-G-372846"
      },
      "category": "ADMS",
      "dataType": "admsId"
    },
    {
      "name": "gisId",
      "value": {
        "id": "G948367549876"
      },
      "dataType": "gisId"
    }
  ],
  "location": {
    "locationId": "L2378462378",
    "geometry": {
      "type": "Point",
      "coordinates": [ 34.23, -57.56 ]
    }
  }
}

=== piripinui/DE-CIM-Model/DE_CIM_Model/test_data/transformer_test.json
{
  "assetId": "DE-TX12763571265",
  "assetDescription": "Power Transformer in Big Substation",
  "assetStatus": "Installed",
  "industryAttributes": [
    {
      "txtype": {
        "manufacturer": "ABB",
        "type": "Power Transformer"
      }
    },
    {
      "txrating": "315 kVA"
    }
  ],
  "customAttributes": [
    {
      "name": "admsId",
      "value": "TX-P-3247",
      "category": "ADMS",
      "dataType": "admsId"
    },
    {
      "name": "gisId",
      "value": "TX-3478564378",
      "dataType": "gisId"
    }
  ],
  "workOrders": [
    {
      "workOrderId": "WO283745636485",
      "workDescription": "Inspect the transformer's gas",
      "startDate": "12/05/19",
      "workOrderStatus": "Complete",
      "assetId": "TX12763571265",
      "secondaryAttributes": [
        {
          "name": "warning",
          "value": "Beware of the dog",
          "category": "WFM",
          "dataType": "string"
        }
      ]
    },
    {
      "workOrderId": "WO283745636485",
      "workDescription": "Fix the transformer",
      "startDate": "14/05/19",
      "workOrderStatus": "Complete",
      "assetId": "TX12763571265",
      "secondaryAttributes": [
        {
          "name": "warning",
          "value": "Beware of the dog",
          "category": "WFM",
          "dataType": "string"
        }
      ]
    }
  ],
  "location": {
    "locationId": "L2378462378",
    "geometry": {
      "type": "Point",
      "coordinates": [ 34.23, -57.56 ]
    }
  }
}
