=== piripinui/DE-CIM-Model/DE_CIM_Model/abb.eam.component-1.0.0.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "abb.eam.component-1.0.0.json",
  "title": "Generic Component Model",
  "description": "The generic model of a Component",

  "$comment": "Below is the definition of component itself.",

  "type": "object",
  "properties": {
    "componentId": {
      "type": "string",
      "description": "The unique identifier for a Component"
    },
    "componentDescription": {
      "type": "string",
      "description": "An information description of the Component"
    },
    "secondaryAttributes": {
      "type": "array",
      "items": { "$ref": "abb.eam.component.secondaryattribute-1.0.0.json" },
      "default": [],
      "description": "A set of attributes associated with the Component"
    },
    "parentAssetId": {
      "type": "string",
      "description": "The identifier of the Asset that is the parent of this Component (Component must have Asset parents)"
    },
    "assets": {
      "type": "array",
      "items": { "$ref": "abb.eam.asset-1.0.0.json" },
      "maxItems": 1,
      "default": [],
      "description": "The set of Assets that are parents of this Component (can only be one)"
    },
    "subcomponents": {
      "type": "array",
      "items": { "$ref": "abb.eam.component-1.0.0.json" },
      "default": [],
      "description": "The set of Components that are sub-components of this Component"
    }
  },
  "required": [
    "componentId", "componentDescription", "secondaryAttributes"
  ],
  "additionalProperties": false
}

=== piripinui/DE-CIM-Model/DE_CIM_Model/test_data/generic_component_test.json
{
  "componentId": "mycomponent123",
  "componentDescription": "Generic component",
  "parentAssetId": "myasset123",
  "secondaryAttributes": [
    {
      "name": "colour",
      "value": "Pink",
      "category": "Appearance",
      "dataType": "string"
    }
  ],
  "assets": [],
  "subcomponents": []
}
