=== piripinui/DE-CIM-Model/schema-server/public/DE_CIM_Model/abb.eam.asset.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "http://localhost/DE_CIM_Model/abb.eam.asset.json",
    "type": "object",
    "title": "Asset Model",
    "properties": {
        "assetId": {
            "type": "string"
        },
        "assetDescription": {
            "type": "string"
        },
        "assetStatus": {
            "$ref": "#assetStatusTypes"
        },
        "assetCriticality": {
            "type": "string",
            "enum": [
                "High",
                "Medium",
                "Low"
            ]
        },
        "secondaryAttributes": {
            "type": "array",
            "default": [],
            "items": {
                "$ref": "#assetSecondaryAttribute"
            }
        },
        "workOrders": {
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.workorder.json"
            }
        },
        "location": {
            "$ref": "abb.eam.location.json"
        },
        "parentAssetId": {
            "type": "string"
        },
        "subassets": {
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.asset.json"
            }
        },
        "subcomponents": {
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.component.json"
            }
        },
        "features": {
            "type": "array",
            "default": [],
            "items": {
                "$ref": "abb.eam.feature.json"
            }
        }
    },
    "required": [
        "assetId",
        "assetDescription",
        "assetStatus",
        "secondaryAttributes"
    ],
    "model-metadata": {
        "model-version": "1.0.0",
        "model-name": "abb.eam.asset.json"
    },
    "$comment": "Below is the definition of asset itself. Note that an Asset may have associated sub-assets, sub-components and features.",
    "definitions": {
        "assetStatusSypes": {
            "$id": "#assetStatusTypes",
            "type": "string",
            "enum": [
                "Installed",
                "Proposed",
                "Abandoned",
                "Active"
            ]
        },
        "assetSecondaryAttribute": {
            "$id": "#assetSecondaryAttribute",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "dataType": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "value"
            ]
        }
    }
}

=== piripinui/DE-CIM-Model/DE_CIM_Model/test_data/generic_sub_asset_test.json
{
  "assetId": "mysubasset943857123",
  "assetDescription": "Generic Sub-Asset object",
  "assetStatus": "Installed",
  "secondaryAttributes": [
    {
      "name": "admsId",
      "value": "346-43564574",
      "category": "ADMS",
      "dataType": "admsId"
    },
    {
      "name": "otherNotes",
      "value": "Near the brick wall in the substation",
      "category": "ADMS",
      "dataType": "string"
    },
    {
      "name": "gisId",
      "value": "12344534",
      "dataType": "gisId"
    }
  ],
  "workOrders": [
    {
      "workOrderId": "WO283745636485",
      "workDescription": "Inspect the asset",
      "startDate": "12/05/19",
      "workOrderStatus": "Complete",
      "assetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "warning",
          "value": "Beware of the dog",
          "category": "WFM",
          "dataType": "string"
        }
      ]
    },
    {
      "workOrderId": "WO283745636485",
      "workDescription": "Fix the asset",
      "startDate": "14/05/19",
      "workOrderStatus": "Complete",
      "assetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "warning",
          "value": "Beware of the dog",
          "category": "WFM",
          "dataType": "string"
        }
      ]
    }
  ],
  "location": {
    "locationId": "L2378462378",
    "geometry": {
      "type": "Point",
      "coordinates": [ 34.23, -57.56 ]
    }
  }
}

=== piripinui/DE-CIM-Model/DE_CIM_Model/test_data/generic_asset_test.json
{
  "assetId": "DE-myasset123",
  "assetDescription": "Generic Asset 12345",
  "assetStatus": "Under Repair",
  "secondaryAttributes": [
    {
      "name": "admsId",
      "value": {
        "id": "346-43564574"
      },
      "category": "ADMS",
      "dataType": "admsId"
    },
    {
      "name": "otherNotes",
      "value": {
        "val": "Near the brick wall in the substation"
      },
      "category": "ADMS",
      "dataType": "string"
    },
    {
      "name": "gisId",
      "value": {
        "id": "12344534"
      },
      "dataType": "gisId"
    }
  ],
  "workOrders": [
    {
      "workOrderId": "WO283745636485",
      "workDescription": "Inspect the asset",
      "startDate": "12/05/19",
      "workOrderStatus": "Complete",
      "parentAssetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "warning",
          "value": "Beware of the dog",
          "category": "WFM",
          "dataType": "string"
        }
      ]
    },
    {
      "workOrderId": "WO283745636485",
      "workDescription": "Fix the asset",
      "startDate": "14/05/19",
      "workOrderStatus": "Complete",
      "parentAssetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "warning",
          "value": "Beware of the dog",
          "category": "WFM",
          "dataType": "string"
        }
      ]
    }
  ],
  "location": {
    "locationId": "L2378462378",
    "geometry": {
      "type": "Point",
      "coordinates": [ 34.23, -57.56 ]
    }
  },
  "subcomponents": [
    {
      "componentId": "mycomponent123",
      "componentDescription": "Generic component",
      "parentAssetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "colour",
          "value": "Pink",
          "category": "Appearance",
          "dataType": "string"
        }
      ],
      "assets": [],
      "subcomponents": []
    },
    {
      "componentId": "complexcomponent123",
      "componentDescription": "Generic component with a subcomponent",
      "parentAssetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "colour",
          "value": "Pink",
          "category": "Appearance",
          "dataType": "string"
        }
      ],
      "assets": [],
      "subcomponents": [
        {
          "componentId": "subcomponent123",
          "componentDescription": "A generic subcomponent with no children",
          "parentAssetId": "myasset123",
          "secondaryAttributes": [
            {
              "name": "colour",
              "value": "Pink",
              "category": "Appearance",
              "dataType": "string"
            }
          ],
          "assets": [],
          "subcomponents": []
        }
      ]
    }
  ]
}

=== piripinui/DE-CIM-Model/DE_CIM_Model/test_data/simple_transformer_test.json
{
  "assetId": "DE-12763571265",
  "assetDescription": "Power Transformer in Big Substation",
  "assetStatus": "Installed",
  "secondaryAttributes": [
    {
      "name": "txtype",
      "value": {
        "txtype": "Power Transformer",
        "manufacturer": "ABB"
      },
      "dataType": "abb.eam.asset.utilities.transformer.secondaryattribute.txtype-1.0.0.json"
    },
    {
      "name": "txrating",
      "value": {
        "rating": "315 kVA"
      },
      "dataType": "abb.eam.asset.utilities.transformer.secondaryattribute.txrating-1.0.0.json"
    },
    {
      "name": "admsId",
      "value": {
        "id": "TX-P-3247"
      },
      "category": "ADMS"
    },
    {
      "name": "gisId",
      "value": {
        "id": "TX-3478564378"
      }
    }
  ],
  "location": {
    "locationId": "L2378462378",
    "geometry": {
      "type": "Point",
      "coordinates": [ 34.23, -57.56 ]
    }
  }
}

=== piripinui/DE-CIM-Model/schema-server/public/test_data/bus_asset_test.json
{
  "assetId": "DE-AS349221",
  "assetDescription": "Mercedes Bus X345",
  "assetStatus": "Active",
  "location": {
    "locationId": "L2378462378",
    "geometry": {
      "type": "Point",
      "coordinates": [ 34.23, -57.56 ]
    }
  },
  "secondaryAttributes": [
    {
      "name": "modelItemId",
      "value": {
        "modelid": "10001"
      },
      "category": "BUS",
      "dataType": "abb.eam.asset.transportation.mercedes-bus-x345.secondaryattribute.modelitemid-1.0.0.json"
    }
  ],
  "subcomponents": [
	   {
    	  "componentId": "TYRE32876578423",
    	  "componentDescription": "Bus Tyre",
    	  "parentAssetId": "AS349221",
    	  "secondaryAttributes": [
      		{
      		  "name": "tyresize",
      		  "value": {
              "tyresize": 48
            },
      		  "category": "TYRES",
      		  "dataType": "abb.eam.component.transportation.mercedes-bus-x345.secondaryattribute.tyresize-1.0.0.json"
      		},
          {
      		  "name": "tyreposition",
      		  "value": {
              "tyreposition": "Front Right"
            },
      		  "category": "TYRES",
      		  "dataType": "abb.eam.component.transportation.mercedes-bus-x345.secondaryattribute.tyreposition-1.0.0.json"
      		}
        ]
      },
      {
     	  "componentId": "TYRE32876578423",
     	  "componentDescription": "Bus Tyre",
     	  "parentAssetId": "AS349221",
     	  "secondaryAttributes": [
       		{
       		  "name": "tyresize",
       		  "value": {
               "tyresize": 48
             },
       		  "category": "TYRES",
       		  "dataType": "abb.eam.component.transportation.mercedes-bus-x345.secondaryattribute.tyresize-1.0.0.json"
       		},
           {
       		  "name": "tyreposition",
       		  "value": {
               "tyreposition": "Front Left"
             },
       		  "category": "TYRES",
       		  "dataType": "abb.eam.component.transportation.mercedes-bus-x345.secondaryattribute.tyreposition-1.0.0.json"
       		}
         ]
       },
       {
      	  "componentId": "TYRE32876578423",
      	  "componentDescription": "Bus Tyre",
      	  "parentAssetId": "AS349221",
      	  "secondaryAttributes": [
        		{
        		  "name": "tyresize",
        		  "value": {
                "tyresize": 52
              },
        		  "category": "TYRES",
        		  "dataType": "abb.eam.component.transportation.mercedes-bus-x345.secondaryattribute.tyresize-1.0.0.json"
        		},
            {
        		  "name": "tyreposition",
        		  "value": {
                "tyreposition": "Back Left"
              },
        		  "category": "TYRES",
        		  "dataType": "abb.eam.component.transportation.mercedes-bus-x345.secondaryattribute.tyreposition-1.0.0.json"
        		}
          ]
        },
        {
       	  "componentId": "TYRE32876578423",
       	  "componentDescription": "Bus Tyre",
       	  "parentAssetId": "AS349221",
       	  "secondaryAttributes": [
         		{
         		  "name": "tyresize",
         		  "value": {
                 "tyresize": 52
               },
         		  "category": "TYRES",
         		  "dataType": "abb.eam.component.transportation.mercedes-bus-x345.secondaryattribute.tyresize-1.0.0.json"
         		},
             {
         		  "name": "tyreposition",
         		  "value": {
                 "tyreposition": "Back Left"
               },
         		  "category": "TYRES",
         		  "dataType": "abb.eam.component.transportation.mercedes-bus-x345.secondaryattribute.tyreposition-1.0.0.json"
         		}
           ]
         }
	 ]
}
