=== piripinui/DE-CIM-Model/schema-server/public/DE_CIM_Model/abb.eam.assethierarchy-1.0.0.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "abb.eam.assethierachy-1.0.0.json",
  "title": "Asset Hierarchy Model",
  "description": "The generic model of the Asset, Component and Feature hierarchy",

  "$comment": "This is a definition of a generic asset hierarchy that can be used for anything",

  "type": "object",
  "properties": {
    "root": {
      "$ref": "abb.eam.asset-1.0.0.json"
    },
    "subassets": {
      "type": "array",
      "items": { "$ref": "abb.eam.asset-1.0.0.json" },
      "default": []
    },
    "subcomponents": {
      "type": "array",
      "items": { "$ref": "abb.eam.component-1.0.0.json" },
      "default": []
    },
    "features": {
      "type": "array",
      "items": { "$ref": "abb.eam.feature-1.0.0.json" },
      "default": []
    }
  },
  "requires": [
    "root", "subassets", "subcomponents", "features"
  ]
}

=== piripinui/DE-CIM-Model/schema-server/public/test_data/generic_asset_hierarchy_test.json
{
  "root": {
      "assetId": "myasset123",
      "assetDescription": "Generic Asset 12345",
      "assetStatus": "Installed",
      "secondaryAttributes": [
        {
          "name": "admsId",
          "value": "346-43564574",
          "category": "ADMS",
          "dataType": "admsId"
        },
        {
          "name": "otherNotes",
          "value": "Near the brick wall in the substation",
          "category": "ADMS",
          "dataType": "string"
        },
        {
          "name": "gisId",
          "value": "12344534",
          "dataType": "gisId"
        }
      ],
      "workOrders": [
        {
          "workOrderId": "WO283745636485",
          "workDescription": "Inspect the asset",
          "startDate": "12/05/19",
          "workorderStatus": "Complete",
          "parentAssetId": "myasset123",
          "secondaryAttributes": [
            {
              "name": "warning",
              "value": "Beware of the dog",
              "category": "WFM",
              "dataType": "string"
            }
          ]
        },
        {
          "workOrderId": "WO283745636485",
          "workDescription": "Fix the asset",
          "startDate": "14/05/19",
          "workorderStatus": "Complete",
          "parentAssetId": "myasset123",
          "secondaryAttributes": [
            {
              "name": "warning",
              "value": "Beware of the dog",
              "category": "WFM",
              "dataType": "string"
            }
          ]
        }
      ],
      "location": {
        "locationId": "L2378462378",
        "geometry": {
          "type": "Point",
          "coordinates": [ 34.23, -57.56 ]
        }
      }
  },
  "subassets": [
    {
      "assetId": "mysubasset943857123",
      "assetDescription": "Generic Sub-Asset object",
      "assetStatus": "Installed",
      "secondaryAttributes": [
        {
          "name": "admsId",
          "value": "346-43564574",
          "category": "ADMS",
          "dataType": "admsId"
        },
        {
          "name": "otherNotes",
          "value": "Near the brick wall in the substation",
          "category": "ADMS",
          "dataType": "string"
        },
        {
          "name": "gisId",
          "value": "12344534",
          "dataType": "gisId"
        }
      ],
      "workOrders": [
        {
          "workOrderId": "WO283745636485",
          "workDescription": "Inspect the asset",
          "startDate": "12/05/19",
          "workorderStatus": "Complete",
          "assetId": "myasset123",
          "secondaryAttributes": [
            {
              "name": "warning",
              "value": "Beware of the dog",
              "category": "WFM",
              "dataType": "string"
            }
          ]
        },
        {
          "workOrderId": "WO283745636485",
          "workDescription": "Fix the asset",
          "startDate": "14/05/19",
          "workorderStatus": "Complete",
          "assetId": "myasset123",
          "secondaryAttributes": [
            {
              "name": "warning",
              "value": "Beware of the dog",
              "category": "WFM",
              "dataType": "string"
            }
          ]
        }
      ],
      "location": {
        "locationId": "L2378462378",
        "geometry": {
          "type": "Point",
          "coordinates": [ 34.23, -57.56 ]
        }
      }
    }
  ],
  "subcomponents": [
    {
      "componentId": "mycomponent123",
      "componentDescription": "Generic component",
      "assetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "inventoryComponentId",
          "value": "346-43564574",
          "category": "Inventory",
          "dataType": "string"
        }
      ]
    },
    {
      "componentId": "mycomponent456",
      "componentDescription": "Generic component",
      "assetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "inventoryComponentId",
          "value": "346-43564574",
          "category": "Inventory",
          "dataType": "string"
        }
      ]
    }
  ],
  "features": [
    {
      "featureId": "myFeature123",
      "featureDescription": "Generic Feature",
      "parentAssetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "colour",
          "value": "Pink",
          "category": "Appearance",
          "dataType": "string"
        }
      ],
      "assets": []
    },
    {
      "featureId": "myFeature456",
      "featureDescription": "Generic Feature",
      "parentAssetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "colour",
          "value": "Blue",
          "category": "Appearance",
          "dataType": "string"
        }
      ],
      "assets": []
    }
  ]
}

=== piripinui/DE-CIM-Model/schema-server/public/test_data/example_bus_hierarchy_specific.json
{
  "root": {
    "assetId": "DE-AS349221",
    "assetDescription": "Mercedes Bus X345",
    "assetStatus": "Active",
    "location": {
      "locationId": "L2378462378",
      "geometry": {
        "type": "Point",
        "coordinates": [ 34.23, -57.56 ]
      }
    },
    "secondaryAttributes": [
      {
        "name": "modeItemId",
        "value": "10001",
        "category": "BUS",
        "dataType": "string"
      }
    ]
  },
  "subassets": [
    {
      "assetId": "DE-E9438758576549",
      "assetDescription": "Mercedes Bus Engine",
      "assetStatus": "Active",
      "fuelType": "Diesel",
      "secondaryAttributes": [
        {
          "name": "enginesize",
          "value": "6L",
          "category": "BUS",
          "dataType": "string"
        }
      ]
    }
  ],
  "subcomponents": [
    {
      "componentId": "DE-TYRE32876578423",
      "componentDescription": "Bus Tyre",
      "parentAssetId": "AS349221",
      "tyreSize": 48,
      "tyrePosition": "Back Left",
      "secondaryAttributes": [
        {
          "name": "manufacturer",
          "value": "Kumho",
          "category": "TYRES",
          "dataType": "string"
        }
      ],
      "assets": []
    },
    {
      "componentId": "DE-TYRE5687966798",
      "componentDescription": "Bus Tyre",
      "parentAssetId": "AS349221",
      "tyreSize": 48,
      "tyrePosition": "Back Right",
      "secondaryAttributes": [
        {
          "name": "manufacturer",
          "value": "Kumho",
          "category": "TYRES",
          "dataType": "string"
        }
      ],
      "assets": []
    },
    {
      "componentId": "DE-TYRE43095394067",
      "componentDescription": "Bus Tyre",
      "parentAssetId": "AS349221",
      "tyreSize": 43,
      "tyrePosition": "Front Left",
      "secondaryAttributes": [
        {
          "name": "manufacturer",
          "value": "Kumho",
          "category": "TYRES",
          "dataType": "string"
        }
      ],
      "assets": []
    },
    {
      "componentId": "DE-TYRE2385734687394",
      "componentDescription": "Bus Tyre",
      "parentAssetId": "AS349221",
      "tyreSize": 43,
      "tyrePosition": "Front Right",
      "secondaryAttributes": [
        {
          "name": "manufacturer",
          "value": "Kumho",
          "category": "TYRES",
          "dataType": "string"
        }
      ],
      "assets": []
    }
  ],
  "features": [
    {
      "featureId": "DE-myFeature123",
      "featureDescription": "Generic Feature",
      "parentAssetId": "myasset123",
      "secondaryAttributes": [
        {
          "name": "colour",
          "value": "Pink",
          "category": "Appearance",
          "dataType": "string"
        }
      ],
      "assets": []
    }
  ]
}
